{
 "title": "Fedstellar",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokiDataSourceUid", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Visitors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "geomap",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({filename=\"/var/log/nginx/analytics.log\"} | json | status = 200 [$__interval])) ",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({filename=\"/var/log/nginx/analytics.log\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "Visitors per hour",
   "type": "stat",
   "description": "Different IP addresses",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by(remote_addr) (count_over_time({filename=\"/var/log/nginx/analytics.log\"} | json [$__auto])))"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 4 },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Successfully Requested Pages",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (request_uri) (count_over_time({filename=\"/var/log/nginx/analytics.log\"} | json | status = 200 [$__interval]))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=\"/var/log/nginx/analytics.log\"} | json [$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Attackers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "geomap",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({filename=\"/var/log/nginx/analytics.log\"} | json | status = 403 [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 25 },
   "targets": [
    { "panelId": 14 }
   ]
  },
  {
   "title": "Top Attackers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (client) (count_over_time({filename=\"/var/log/nginx/error.log\"} |= \"ModSecurity\" |= \"error\" | pattern \"<date> <time> [<level>] <_> ModSecurity: <modsec_action> [file \\\"/etc/modsecurity.d/owasp-crs/rules/<rule_set>.conf<_> [id \\\"<rule_id>\\\"<_> [msg \\\"<msg>\\\"] <_>[ver \\\"<owasp_version>\\\"]<_>] [tag <tags>] [host<_>, client: <client>, server: <server>, request: \\\"<request_method> <ressource> <http_version>\\\", <_>\" |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{.client}}"
    }
   ]
  },
  {
   "title": "Error Logs  ➡️ only ModSecurity",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/nginx/error.log\"} |= \"ModSecurity\" |= \"error\" | pattern \"<date> <time> [<level>] <_> ModSecurity: <modsec_action> [file \\\"/etc/modsecurity.d/owasp-crs/rules/<rule_set>.conf<_> [id \\\"<rule_id>\\\"<_> [msg \\\"<msg>\\\"] <_>[ver \\\"<owasp_version>\\\"]<_>] [tag <tags>] [host<_>, client: <client>, server: <server>, request: \\\"<request_method> <ressource> <http_version>\\\", <_>\"\r\n\r\n| line_format \" {{.date}} {{.time}} {{.server}} {{.request_method}} {{.ressource}} ❗️☠️ {{.client}} ☠️️❗️ \\n➡️ RuleSet: {{.rule_set}} RuleId: {{.rule_id}} {{.msg}}\\n [tag {{.tags}}]\""
    }
   ]
  },
  {
   "title": "Attacks/Ressource",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (ressource) (count_over_time({filename=\"/var/log/nginx/error.log\"} |= \"ModSecurity\" |= \"error\" | pattern \"<date> <time> [<level>] <_> ModSecurity: <modsec_action> [file \\\"/etc/modsecurity.d/owasp-crs/rules/<rule_set>.conf<_> [id \\\"<rule_id>\\\"<_> [msg \\\"<msg>\\\"] <_>[ver \\\"<owasp_version>\\\"]<_>] [tag <tags>] [host<_>, client: <client>, server: <server>, request: \\\"<request_method> <ressource> <http_version>\\\", <_>\" |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{ressource}}"
    }
   ]
  },
  {
   "title": "Error Logs All",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/nginx/error.log\"}"
    }
   ]
  }
 ]
}