name: "setup-env"
description: "Set up a Python environment"

inputs:
  python-version:
    required: false
    description: "The version of Python"
    default: "3.11.7"

runs:
  using: "composite"
  steps:
    - name: Set up python
      run: |
        curl -fsSL https://astral.sh/uv/install.sh | bash
        uv python install ${{ inputs.python-version }}
        uv python pin ${{ inputs.python-version }}
      shell: bash

    - name: Add uv to Path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Cache virtual environment
      id: cache-venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}

    - name: Install dependencies if cache is not hit
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: uv sync
      shell: bash
